container:
  image: archlinux:latest
  cpu: 2
  memory: 2G
  options: --user root

env:
  DEPLOY_KEY: ENCRYPTED[489ea965063f2189762e65c79c9e670efb632d4833f20e6cd151de6cc212390300930469639a1e85366a2155714a0a16]
  PUBDIR: "output"
  ORIGIN: "git@github.com:iacchus/iacchus.github.io.git"

build_and_publish_task:
  auto_cancellation: $CIRRUS_CHANGE_TITLE == 'auto from cirrus-ci'
  prepare_archlinux_script:
    - pacman -Syu --noconfirm
    - pacman -Fy
    - echo 'en_US.UTF-8 UTF-8' >> /etc/locale.gen
    - echo 'LANG=en_US.UTF-8' > /etc/locale.conf        
    - locale-gen
    - pacman-key --init
    - pacman -Syu --noconfirm git python python-pip pelican openssh make python-markdown
  prepare_ssh_script:
    - mkdir -p ~/.ssh/
    - echo -e "${DEPLOY_KEY}" > ~/.ssh/deploy_key
    - chmod 600 ~/.ssh/deploy_key
    - echo 'Host github.com'                  >  ~/.ssh/config
    - echo '  HostName github.com'            >> ~/.ssh/config
    - echo '  User git'                       >> ~/.ssh/config
    - echo '  IdentityFile ~/.ssh/deploy_key' >> ~/.ssh/config
    - ssh-keyscan -t rsa github.com > ~/.ssh/known_hosts
  prepare_git_script:
    - git config --global push.default matching
    - git config --global user.email "kassivs+git@gmail.com"
    - git config --global user.name "I.M. - Cirrus-CI"
    - git config --global init.defaultBranch master
    #- rm -rf .git/
  build_and_publish_script:
    - git clone https://github.com/iacchus/iacchus.github.io-pelican.git pelican
    - cd pelican
    - rm -rf .git/
    - git clone https://github.com/iacchus/blog-posts.git content
    - make publish
    - cd $PUBDIR
    - git init .
    - git add .
    - git commit -a -m 'auto from cirrus-ci' || true
    - git remote add origin $ORIGIN
    - git push --force -u origin master
